//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliGest.BackEnd.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionPolideportivaEntities : DbContext
    {
        public GestionPolideportivaEntities()
            : base("name=GestionPolideportivaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dia> dia { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<instalacion> instalacion { get; set; }
        public virtual DbSet<instalaciones_tiene_horario> instalaciones_tiene_horario { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<socios> socios { get; set; }
        public virtual DbSet<tipo_instalacion> tipo_instalacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
