//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliGest.BackEnd.Modelo
{
    using PoliGest.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class reserva : PropertyChangedDataError
    {
        public int idreserva { get; set; }

        [Required(ErrorMessage = "Este campo obligatorio")]
        public System.DateTime fecha_reserva { get; set; }

        public System.TimeSpan hora_inicio { get; set; }

        public System.TimeSpan hora_fin { get; set; }

        [Required(ErrorMessage = "Este campo obligatorio")]
        public double precio { get; set; }
        public sbyte no_presentado { get; set; }
        public sbyte anulado { get; set; }

        [Required(ErrorMessage = "Este campo obligatorio")]
        public sbyte pagado { get; set; }
        public int instalacion_idinstalacion { get; set; }
        public int usuario_idusuario { get; set; }

        [Required(ErrorMessage = "Este campo obligatorio")]
        public virtual instalacion instalacion { get; set; }

        [Required(ErrorMessage = "Este campo obligatorio")]
        public virtual usuario usuario { get; set; }
    }
}
