//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliGest.BackEnd.Modelo
{
    using PoliGest.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tipo_instalacion : PropertyChangedDataError
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_instalacion()
        {
            this.instalacion = new HashSet<instalacion>();
            this.instalaciones_tiene_horario = new HashSet<instalaciones_tiene_horario>();
        }
    
        public int idtipo { get; set; }

        [Required(ErrorMessage = "Este campo obligatorio")]
        [StringLength(80, ErrorMessage = "La descrición es demasiado larga")]
        public string descripcion { get; set; }

        [Required(ErrorMessage = "Este campo obligatorio")]
        public int tiempo_max { get; set; }

        [Required(ErrorMessage = "Este campo obligatorio")]
        public double precio_hora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instalacion> instalacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instalaciones_tiene_horario> instalaciones_tiene_horario { get; set; }
    }
}
